# 
name: ethzero.github.com
markdown: rdiscount
future: true


exclude:
- .gitignore
- README.md

navigation:
- text: What we do
  url: /en/what-we-do/
- text: Who we are
  url: /en/who-we-are/
- text: Projects
  url: /en/projects/
- text: Blog
  url: /en/blog/
  layout: post
